version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10
      versioning-strategy: increase
      groups:
          production:
              dependency-type: production
          development:
              dependency-type: development
      ignore:
          - dependency-name: "*"
            update-types:
                - version-update:semver-patch

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
