version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
      open-pull-requests-limit: 10
      versioning-strategy: increase
      groups:
          production:
              dependency-type: production
          development:
              dependency-type: development
              exclude-patterns:
                  - "*eslint*"
      ignore:
          - dependency-name: "*"
            update-types:
                - version-update:semver-patch
          - dependency-name: "*eslint*"
            update-types:
                - version-update:semver-major
                - version-update:semver-minor
                - version-update:semver-patch

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
